install.packages("palmerpenguins")
install.packages("here")
require(palmerpenguins)
require(here)
class(penguins)
mean(penguins$body_mass_g)
head(penguins)
mean(penguins)
summary(penguins)
plot(penguins)
plot(species)
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(1, 2)) 
